### ISSUE TITLE
[Feature Request] Custom Sounds

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/PlayerBosses#1]
Hey! 

Could you make it possible to add custom sounds to the boss? Right now I believe it uses vanilla zombie sounds so we can't override just this one mob. Can you give bosses a generic sound and we can use resource loader to assign some custom sounds?

Thank you!

**Comment by Lothrazar** [comment]
i think this should work https://minecraft.curseforge.com/projects/giant-player-boss/files/2728120
